[package]
name = "node-testing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
pallet-balances = { package = "pallet-balances", default-features = false, path = "../pallets/balances", version = "2.0.0" }
sc-service = { version = "0.8.0", features = ["test-helpers", "db"]}
sc-client-db = { version = "0.8.0",features = ["kvdb-rocksdb", "parity-db"] }
sc-client-api = '2.0.0'
codec = { package = "parity-scale-codec", version = "1.3.4" }
pallet-contracts ='2.0.0'
pallet-grandpa = '2.0.0'
pallet-indices = '2.0.0'
sp-keyring = '2.0.0'
node-executor = { version = "2.0.0", path = "../executor" }
node-primitives = { version = "2.0.0", path = "../primitives" }
e2-chain-runtime = { version = "2.0.0", path = "../runtime" }
sp-core = '2.0.0'
sp-io = '2.0.0'
frame-support = '2.0.0'
pallet-session = '2.0.0'
pallet-society = '2.0.0'
sp-runtime = '2.0.0'
pallet-staking_with_credit = {package = "pallet-staking_with_credit", default-features = false, path = "../pallets/staking_with_credit", version = "2.0.0"}
sc-executor = { version = "0.8.0", features = ["wasmtime"] }
sp-consensus = '0.8.0'
frame-system = '2.0.0'
substrate-test-client = { version = "2.0.0", path = "../test-client" } 
pallet-timestamp = '2.0.0'
pallet-transaction-payment = '2.0.0'
pallet-treasury = '2.0.0'
sp-api = '2.0.0'
sp-finality-tracker = { version = "2.0.0", default-features = false}
sp-timestamp = { version = "2.0.0", default-features = false}
sp-block-builder = '2.0.0'
sc-block-builder = '0.8.0'
sp-inherents = '2.0.0'
sp-blockchain = '2.0.0'
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"

[dev-dependencies]
criterion = "0.3.0"
sc-cli = '0.8.0'
