[package]
name = "node-cli"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic Substrate node implementation in Rust."
build = "build.rs"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
default-run = "e2-chain"
homepage = "https://deepernetwork.io"
repository = "https://github.com/e2chain-dev/e2-chain-v2.0.0"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "paritytech/substrate" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "e2-chain"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.4" }
serde = { version = "1.0.102", features = ["derive"] }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.3.1"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
tracing = "0.1.19"
parking_lot = "0.10.0"

# primitives
sp-authority-discovery = '2.0.0'
sp-consensus-babe = '0.8.0'
grandpa-primitives = { version = "2.0.0", package = "sp-finality-grandpa"}
sp-core = '2.0.0'
sp-runtime = '2.0.0'
sp-timestamp = { version = "2.0.0", default-features = false}
sp-finality-tracker = { version = "2.0.0", default-features = false}
sp-inherents = '2.0.0'
sp-keyring = '2.0.0'
sp-io = '2.0.0'
sp-consensus = '0.8.0'
sp-transaction-pool = '2.0.0'

# client dependencies
sc-client-api = '2.0.0'
sc-chain-spec = '2.0.0'
sc-consensus = '0.8.0'
sc-transaction-pool ='2.0.0' 
sc-network = '0.8.0'
sc-consensus-babe = '0.8.0'
grandpa = { version = "0.8.0", package = "sc-finality-grandpa"}
sc-client-db = { version = "0.8.0", default-features = false}
sc-offchain = '2.0.0'
sc-rpc = '2.0.0'
sc-basic-authorship = '0.8.0'
sc-service = { version = "0.8.0", default-features = false}
sc-tracing = '2.0.0'
sc-telemetry = '2.0.0'
sc-authority-discovery = '0.8.0'

# frame dependencies
pallet-indices =  '2.0.0'
pallet-timestamp = { version = "2.0.0", default-features = false}
pallet-contracts =  '2.0.0'
frame-system =  '2.0.0'
pallet-balances = { package = "pallet-balances", default-features = false, path = "../pallets/balances", version = "2.0.0" }
pallet-transaction-payment =  '2.0.0'
frame-support = { version = "2.0.0", default-features = false}
pallet-im-online = { version = "2.0.0", default-features = false}
pallet-authority-discovery = '2.0.0' 
pallet-staking_with_credit = {package = "pallet-staking_with_credit", default-features = false, path = "../pallets/staking_with_credit", version = "2.0.0"}
pallet-grandpa = '2.0.0'

# node-specific dependencies
e2-chain-runtime = { version = "2.0.0", path = "../runtime" }
node-rpc = { version = "2.0.0", path = "../rpc" }
node-primitives = { version = "2.0.0", path = "../primitives" }
node-executor = { version = "2.0.0", path = "../executor" }

# CLI-specific dependencies
sc-cli = { version = "0.8.0", optional = true}
frame-benchmarking-cli = { version = "2.0.0", optional = true}
node-inspect = { version = "0.8.0", optional = true, path = "../inspect" }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "substrate-browser-utils", optional = true, version = "0.8.0"}

[target.'cfg(target_arch="x86_64")'.dependencies]
node-executor = { version = "2.0.0", path = "../executor", features = [ "wasmtime" ] }
sc-cli = { version = "0.8.0", optional = true, features = [ "wasmtime" ] }
sc-service = { version = "0.8.0", default-features = false, features = [ "wasmtime" ] }
sp-trie = { version = "2.0.0", default-features = false, features = ["memory-tracker"] }

[dev-dependencies]
sc-keystore = '2.0.0'
sc-consensus = '0.8.0'
sc-consensus-babe = { version = "0.8.0", features = ["test-helpers"]}
sc-consensus-epochs = '0.8.0'
sc-service-test = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0" }
futures = "0.3.4"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.17"
serde_json = "1.0"
regex = "1"
platforms = "0.2.1"

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
node-inspect = { version = "0.8.0", optional = true, path = "../inspect" }
frame-benchmarking-cli = { version = "2.0.0", optional = true}
substrate-build-script-utils = { version = "2.0.0", optional = true}
substrate-frame-cli = { version = "2.0.0", optional = true}

[build-dependencies.sc-cli]
version = "0.8.0"
package = "sc-cli"
optional = true

[features]
default = [ "cli" ]
browser = [
	"browser-utils",
	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
	"node-executor/wasmi-errno",
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
]
runtime-benchmarks = [
	"e2-chain-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
