[package]
authors = ['deeper.network dev']
description = 'credit pallet for PoC in e2-chain.'
edition = '2018'
homepage = 'https://deeper.network'
license = 'Unlicense'
name = 'pallet-credit'
repository = 'https://github.com/e2chain-dev/e2-chain'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dev-dependencies]
sp-io = { version = "2.0.0", default-features = false}
sp-runtime = { version = "2.0.0", default-features = false}
pallet-balances = { version = "2.0.0", default-features = false, path = "../balances" }
pallet-timestamp = { version = "2.0.0", default-features = false}


[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '1.3.4'}
frame-support = { version = "2.0.0", default-features = false}
frame-system = { version = "2.0.0", default-features = false}
sp-core = { version = "2.0.0", default-features = false}
pallet-micropayment = {version = '2.0.0', default-features =false, path = "../micropayment"}
pallet-deeper-node = {version = '2.0.0', default-features =false, path = "../deeper-node"}
sp-std = {version = "2.0.0", default-features = false}
pallet-session = {version = "2.0.0", default-features = false}
node-primitives = {version = '2.0.0', default-features = false, path = "../../primitives"}
sp-runtime = { version = "2.0.0", default-features = false}

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-micropayment/std',
    'pallet-deeper-node/std',
    'sp-std/std',  
    'sp-core/std',
    'sp-runtime/std',
    'node-primitives/std',
    'pallet-session/std',
]
