[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
node-primitives = { version = "2.0.0", path = "../primitives" }
e2-chain-runtime = { version = "2.0.0", path = "../runtime" }
sc-executor = '0.8.0' 
sp-core = '2.0.0'
sp-io = '2.0.0'
sp-state-machine = '0.8.0' 
sp-trie = '2.0.0'
trie-root = "0.16.0"
frame-benchmarking = '2.0.0'

[dev-dependencies]
criterion = "0.3.0"
frame-support = '2.0.0'
frame-system = '2.0.0'
node-testing = { version = "2.0.0", path = "../testing" }
pallet-balances = { package = "pallet-balances", default-features = false, path = "../pallets/balances", version = "2.0.0" }
pallet-contracts = '2.0.0'
pallet-grandpa = '2.0.0'
pallet-im-online = '2.0.0'
pallet-indices = '2.0.0'
pallet-session = '2.0.0'
pallet-timestamp = '2.0.0'
pallet-transaction-payment = '2.0.0'
pallet-treasury = '2.0.0'
sp-application-crypto = '2.0.0'
sp-runtime = '2.0.0'
sp-externalities = '0.8.0'
substrate-test-client = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0" }
wat = "1.0"

[features]
wasmtime = [
	"sc-executor/wasmtime",
]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
