[package]
name = "donut-core"
version = "0.1.0"
authors = ["Wenfeng Wang <kalot.wang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { features = ['derive'], optional = true, version = '1.0.119' }

sp-std = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

frame-benchmarking = { default-features = false, optional = true, version = '3.0.0'  }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }


[features]
default = ['std']
std = [
    'codec/std',
    'serde',
    'sp-std/std',
    'sp-runtime/std',
    "frame-benchmarking/std",
    'frame-support/std',
    'frame-system/std',
]
runtime-benchmarks = ["frame-benchmarking"]
