version: "3.2"

services:
  dev:
    container_name: mintcraft
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/mintcraft
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/mintcraft/.cargo
    volumes:
      - .:/var/www/mintcraft
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/mintcraft --dev --ws-external"
