[package]
name = 'mc-nft'
version = '0.1.0'
authors = ['Tang Bo Hao <tech@btang.cn>','Yin Nan','Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'Mintcraft pallet of nft'
edition = '2018'
license = 'MIT'
homepage = 'https://substrate.dev'
repository = 'https://github.com/btspoony/mintcraft'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-std = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-arithmetic = { default-features = false, version = '3.0.0' }
mc-support = { default-features = false, path = "../support" }

[dev-dependencies]
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
pallet-balances = { default-features = false, version = '3.0.0' }
sp-externalities = { default-features = false, version = "0.9.0" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-std/std',
    'serde',
]
